### ISSUE TITLE
Fontconfig not playing nicely with julia 0.4.2

### ISSUE THREAD

**Issue by amellnik** [dcjones/Fontconfig.jl#2]
I have been using the Gadfly master and the most recent Fontconfig.  Everything was working fine in 0.4.1, but when I switched over to 0.4.2 and ran ```using Gadlfy``` I started seeing errors like

```
INFO: Precompiling module Fontconfig...
ERROR: LoadError: error compiling __init__: could not load library "libfontconfig"
The specified module could not be found.

 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at client.jl:257
 in _start at client.jl:378
while loading C:\Users\amellnik\.julia\v0.4\Fontconfig\src\Fontconfig.jl, in expression starting on line 147
LoadError: Failed to precompile Fontconfig to C:\Users\amellnik\.julia\lib\v0.4\Fontconfig.ji
while loading In[1], in expression starting on line 1

 in error at error.jl:21
```

Interestingly, this also broke Fontconfig in 0.4.1, and even after running ```Pkg.build("Fontconfig")``` I would get the same error in 0.4.1.  Removing the package and reinstalling it allows it to work with 0.4.1, but only until I try to use it in 0.4.2

**Comment by PaulSoderlind** [comment]
+1
(but in 0.4.3 on Windows 7)

**Comment by fbertaux** [comment]
+1
(but 0.4.3 on OSX 10.10.5)

**Comment by fiatflux** [comment]
Also happened to me on OSX 10.9.5 and Julia 0.4.3

Installing the fontconfig library via Homebrew was the ticket.

**Comment by fbanez** [comment]
Sorry, I am new using Julia. How do you install the fontconfig library via Homebrew?

Thanks!

**Comment by fiatflux** [comment]
IIRC it required just
> brew install fontconfig

And that's it...if you already use homebrew

**Comment by fbanez** [comment]
I don't think I use homebrew...

**Comment by fiatflux** [comment]
It's easy to start :-)

**Comment by VassiliosRendoumis** [comment]
Same error here. 
Windows 7, julia 0.4.5

**Comment by yakir12** [comment]
same here: 
Debian stretch, julia 0.4.5

**Comment by Nosferican** [comment]
+1, Win10, Julia 4.6

**Comment by meaningofshape** [comment]
+1, Win7, Julia 0.4.5

**Comment by c-georgen** [comment]
+1, Win10, Julia 0.4.6

**Comment by tlnagy** [comment]
Is this still a problem on 0.5?
