### ISSUE TITLE
Fontconfig install error

### ISSUE THREAD

**Issue by StarkShang** [dcjones/Fontconfig.jl#3]
When I use Fontconfig in Julia 0.4.3, it says "Failed to precompile Fontconfig". What can I do?
I just execute Pkg.add("Fontconfig") in Julia. Should I install other fontconfig files?

**Comment by mlubin** [comment]
Also reported by @chriscoey, OS X 10.11.3 and Julia 0.4.3

**Comment by tlnagy** [comment]
Is this this a problem?
